version: "3.7"

services:
  
# docker run -dp 3000:3000 --network todo-app -e MYSQL_USER=root -e MYSQL_PASSWORD=pass -e MYSQL_DB=todos getting-started:v2
  app:
    image: wusted/getting-started:v2
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_DB: todos
  
# docker run -d --network todo-app --network-alias mysql -v todo-mysql-data:/var/lib/mysql --platform linux/x86_64 \
# -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=todos mysql:5.7
  mysql:
    image: mysql:5.7
    volumes:
      - ./todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: todos